import { Inter } from "next/font/google";
// import { SessionProvider } from "next-auth/react";
// import { Session } from "next-auth";
// import { headers } from "next/headers";

import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import "./globals.css";

const inter = Inter({
    display: "swap",
    weight: ["100", "500", "600", "700"],
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// async function getSession(cookie: string): Promise<Session> {
//     const response = await fetch(
//         `${process.env.LOCAL_AUTH_URL}/api/auth/session`,
//         {
//             headers: {
//                 cookie
//             }
//         }
//     );
//     const session = await response.json();
//
//     return Object.keys(session).length > 0 ? session : null;
// }

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    // const session = await getSession(headers().get("cookie") ?? "");
    return (
        <html lang="en">
            <body className={`bg-slate-900 antialiased ${inter.className}`}>
                <Header />
                <main className="max-w-[1200px] mx-auto">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
