import { Inter } from 'next/font/google'
import { Header } from "./components/Header";
import "./globals.css";

const inter = Inter({
  display: 'swap',
  weight: ['100', '500', '600', '700'],
  variable: '--font-inter',
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-slate-900 antialiased ${inter.className}`}>
        <Header />
        <main className='max-w-[1200px] mx-auto'>{children}</main>
      </body>
    </html>
  );
}
